name: health_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# ... (–í–µ—Ä—Å—ñ—è —Ç–∞ environment –∑–∞–ª–∏—à–∞—é—Ç—å—Å—è –±–µ–∑ –∑–º—ñ–Ω)
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1  # –ê–±–æ –Ω–æ–≤—ñ—à–∞ –≤–µ—Ä—Å—ñ—è
  flutter_dotenv: ^5.1.0

  flutter_localizations:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.5.6 # –¶–µ–π –ø–∞–∫–µ—Ç –ø–æ—Ç—Ä—ñ–±–µ–Ω, —è–∫—â–æ –≤–∏ –∑–∞–ª–∏—à–∏—Ç–µ –º–æ–∂–ª–∏–≤—ñ—Å—Ç—å –∑–∞–≤–∞–Ω—Ç–∞–∂—É–≤–∞—Ç–∏ –≤–ª–∞—Å–Ω—ñ —Ñ–æ—Ç–æ
  table_calendar: ^3.1.2 # (–∞–±–æ –Ω–æ–≤—ñ—à—É –≤–µ—Ä—Å—ñ—é)
  intl: 0.20.2
  # Image handling
  image_picker: ^1.0.4

  # Local DB
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # üöÄ –ê–∫—Ç–∏–≤–∞—Ü—ñ—è –ª–æ–∫–∞–ª—å–Ω–∏—Ö –∞—Å–µ—Ç—ñ–≤ (–ó–ú–Ü–ù–ê –¢–£–¢!)
  # –¶–µ –¥–æ–∑–≤–æ–ª–∏—Ç—å –¥–æ–¥–∞—Ç–∫—É –±–∞—á–∏—Ç–∏ –≤–∞—à—É –ø–∞–ø–∫—É assets/images/
  assets:
    - assets/avatars/
    - assets/doctor_avatars/
    - .env